### ISSUE TITLE
Board Schema

### ISSUE THREAD

**Issue by 1995parham** [kian79/GSM_send_temperature#1]
Can you provide the documentation about the hardware you used and how you set them up? Personally, three/four years ago I want to set up the GSM modem with Arduino without success, so I really love your repository :heart_eyes:

**Comment by kian79** [comment]
I'm really glad you liked it :D
Actually, I did it about 9 months ago and I can't remember exactly the hardware I used. But I found some photos of the project and added them to the repository.
As I remember it was a Sim800L gsm module and an Arduino Uno. But I will try to provide complete documentation and add it to the repository and then close this issue.
Thanks for your attention.
